### ISSUE TITLE
Simplify AntimicrobialResistanceResult.read()

### ISSUE THREAD

**Issue by dfornika** [pha4ge/harmonized-amr-parsers#1]
The [`AntimicrobialResistanceGenomicAnalysisResult.read()`](https://github.com/dfornika/harmonized-amr-parsers/blob/6aff1b3686eb82c2535afabf840e9e731fa40eee/antimicrobial_resistance_result/AntimicrobialResistance/Result.py#L69-L158) method takes a dictionary as input and loads values into the class by matching the keys in the dictionary against the attribute names in the class.

Since each dictionary lookup could fail, each lookup is wrapped in a `try: / except:` block. This leads to a really verbose (and inefficient?) implementation.

There may be a simpler way to convert from a dict to our `AntimicrobialResistanceGenomicAnalysisResult` class via a  [namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple) and/or a [dataclass](https://docs.python.org/3/library/collections.html#collections.namedtuple)

**Comment by fmaguire** [comment]
https://docs.python.org/3/library/dataclasses.html is the solution to this, I'm integrating it into the refactor for #21 #22 #23 I'm currently doing to modularise a lot more of this.
