### ISSUE TITLE
Add parser: Mykrobe

### ISSUE THREAD

**Issue by fmaguire** [pha4ge/harmonized-amr-parsers#17]

**Comment by fmaguire** [comment]
Assigned to @awitney (although I don't seem able to officially assign the issue as @awitney isn't a member of @pha4ge/wg-data_structures yet)

**Comment by fmaguire** [comment]
Deferring this to when we have a mutational/variant AMR specification.

**Comment by awitney** [comment]
Yes, sorry i had a look at this and remembered that its more variant based. Although for Staph sequences i think it does identify the presence of some resistance genes. Probably better to wait for a mutation aware spec though
